### ISSUE TITLE
属性映射的问题

### ISSUE THREAD

**Issue by hrstruggle1** [MoyaMapper/MoyaMapper#10]
"不需要考虑源json数据的真实类型，这里统一按 Model 中属性声明的类型进行转换"

我测试了一下, model 中的 id 为 String, JSON 下发的 id 为 int , 实际 response.mapArray 出来的 models id 为空, 测试的就是 demo 中的 http://jsonplaceholder.typicode.com/users 这个请求

但是把 model 中的 id 改为 Int 就正常映射了

**Comment by LinXunFeng** [comment]
好的，知道原因了，这两天会进行修复和更新，感谢反馈

**Comment by LinXunFeng** [comment]
@hrstruggle1 已修复，请升级使用3.0.1版本
