### ISSUE TITLE
可以考虑把JSON和Model互转的单独抽离出来吗，只保留MMCodable的核心功能

### ISSUE THREAD

**Issue by majie776** [MoyaMapper/MoyaMapper#11]

**Comment by LinXunFeng** [comment]
MMCodable独自做成一个子库？你是想单独依赖使用吗？

**Comment by majie776** [comment]
> MMCodable独自做成一个子库？你是想单独依赖使用吗？

对，当成一个单独的JSON转化依赖使用，主要是你这个json转model的，按照model定义的类型来解析比较好用，比原生的Codable更灵活

**Comment by LinXunFeng** [comment]
我找时间把它抽成一个独立的库吧，感谢你的建议👍

**Comment by LinXunFeng** [comment]
`MMCodable` 已抽离，请使用 `0.0.2` 版本
https://github.com/MoyaMapper/MMCodable
