### ISSUE TITLE
服务器返回的Int不支持自动转成string

### ISSUE THREAD

**Issue by GreatLiyi** [MoyaMapper/MoyaMapper#12]
希望能支持下

**Comment by LinXunFeng** [comment]
> 希望能支持下

你好，想先确认下你现在使用的 `MoyaMapper` 是哪个版本？`3.0.1` 版本是有解决这个问题的

**Comment by GreatLiyi** [comment]
> > 希望能支持下
> 
> 你好，想先确认下你现在使用的 `MoyaMapper` 是哪个版本？`3.0.1` 版本是有解决这个问题的

我用的3.0.0

**Comment by LinXunFeng** [comment]
> > > 希望能支持下
> > 
> > 
> > 你好，想先确认下你现在使用的 `MoyaMapper` 是哪个版本？`3.0.1` 版本是有解决这个问题的
> 
> 我用的3.0.0

那你可以先升级到 `3.0.1` 试下哈

**Comment by LinXunFeng** [comment]
先关闭了，如果有问题的话可以再打开进行评论
