### ISSUE TITLE
有没有做过json转model的速度测试，感觉好慢啊

### ISSUE THREAD

**Issue by GreatLiyi** [MoyaMapper/MoyaMapper#13]

**Comment by LinXunFeng** [comment]
你是用 MoyaMapper Demo 感觉的慢？还是自己项目里使用时感觉的慢？

**Comment by GreatLiyi** [comment]
> 你是用 MoyaMapper Demo 感觉的慢？还是自己项目里使用时感觉的慢？

自己项目里面，数据回来了，但是显示出来还要顿一下

**Comment by GreatLiyi** [comment]
> 你是用 MoyaMapper Demo 感觉的慢？还是自己项目里使用时感觉的慢？

网络数据回来了，json的log已经打印在控制台了，但是显示数据到tableview会蹲一下

**Comment by LinXunFeng** [comment]
建议你那边测试一下转换模型时所消耗的时间，如下方代码所示，确定不是其它原因造成的。
如若确定是 `MoyaMapper` 造成的，请提供版本号（最好能有demo）

```swift
print("start time -- \(Date().timeIntervalSince1970)")

// 转换模型
let models = response.mapArray(MyModel.self)

print("end time -- \(Date().timeIntervalSince1970)")
```

> > 你是用 MoyaMapper Demo 感觉的慢？还是自己项目里使用时感觉的慢？
> 
> 网络数据回来了，json的log已经打印在控制台了，但是显示数据到tableview会蹲一下

**Comment by GreatLiyi** [comment]
> 建议你那边测试一下转换模型时所消耗的时间，如下方代码所示，确定不是其它原因造成的。
> 如若确定是 `MoyaMapper` 造成的，请提供版本号（最好能有demo）
> 
> ```swift
> print("start time -- \(Date().timeIntervalSince1970)")
> 
> // 转换模型
> let models = response.mapArray(MyModel.self)
> 
> print("end time -- \(Date().timeIntervalSince1970)")
> ```
> 
> > > 你是用 MoyaMapper Demo 感觉的慢？还是自己项目里使用时感觉的慢？
> > 
> > 
> > 网络数据回来了，json的log已经打印在控制台了，但是显示数据到tableview会蹲一下

关掉这个issue吧，我懒得看了
