### ISSUE TITLE
关于mapObject解析无效

### ISSUE THREAD

**Issue by StevenZhang1990** [MoyaMapper/MoyaMapper#16]
Log(JSON(response.data)) //打印网络数据
 let user = response.mapObject(UserMsgData.self); //模型转换
 Log("user - " + "\(user.mobile)") //打印模型
 
 mapObject此方法无效，user打印为空，不知可否请教一下zhangwengcd@163.com

**Comment by LinXunFeng** [comment]
我这边的试了是可以的，麻烦提供个`Demo`吧

**Comment by StevenZhang1990** [comment]
下载最高分辨率图像
2021年3月6日过期
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAWiQP8fP50fMbtSE-1AD9Y9lPJbRAQkw2GcApTN9wCVsbgvQpn11ZS7s%2F%24%7Bf%7D%3Fo%3DAq2rMUqucUTfhAC8noBiBLaLc8Ggo0ci93S3rUTXRjdX%26v%3D1%26x%3D3%26a%3DCAogKgxuFf83_NJHqFnhVpSEE3E6sBnJAANihZND17lPZGoSeBCFrPff9i4Yhbzys4AvIgEAKgkC6AMA_0Clb-FSBGU8ltFaBHVlLuxqJm1zBU7NIcHRxAwPMQaBcLPaG0xsoPpwUA34TFtv7dd3_Ak24csKciYaQ-U52Q-cVy3ZiA41KB5FqGYAs65ZnsLhRF0vTtf_uALmTp4lew%26e%3D1615016533%26fl%3D%26r%3D49B78EAB-1156-4106-B229-1B93D3019174-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DE8ED9AA4-CDC6-44DE-8216-1727CFF89F2E%26p%3D36%26s%3DTjcMRCNCeLWnN7fHcT183p40q3M&uk=5UEGGNbSqnFb3x0CTU_IKw&f=Images.zip&sz=56254>感谢作者回复，

断点跟踪了一下，modelValue方法时失败，全局搜索“出现问题的地方”，即可看到这个网络请求，

运行程序，点击“订单” - > 输入手机号“13344445555” -> 输入验证码”1111”，即可触发问题接口




点按以下载
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAT_FB1XhAmpJ2loVm--sPzVk7RnBAZ9KQ1xx94kekWIt0pTytDTq3Zmq%2F%24%7Bf%7D%3Fo%3DApqmNj4sIycxLPLA1NPFnHAKMnIN9ZmLlT99N3JotKYn%26v%3D1%26x%3D3%26a%3DCAogYmUFJvWqTmyZKTPH_glbZzOKiVo8xsA8nHA3G_0vt-sSeBDqp_ff9i4Y6rfys4AvIgEAKgkC6AMA_w0M4_VSBGTtGcFaBOrdmapqJpkbbcKrnkNtiNH6pULSEk6zFhWrHnKMVByY47_VXoO-Z5EMa2HEcibxn4zgVt3-fQf_NAS2eC9oLQ-IdZqq1i-wJP8aK9hT7WcxKdNp2g%26e%3D1615016532%26fl%3D%26r%3D356848B4-350E-4504-8642-5849796B6EC8-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DE8ED9AA4-CDC6-44DE-8216-1727CFF89F2E%26p%3D36%26s%3D1WDvsyzY_-eSvvF4QBtUxS2ZyHQ&uk=GrUA04hryBpkzEoHqQHZMg&f=jxbSwift.zip&sz=21553811>jxbSwift.zip
21.6 MB

版权限制，仅供交流，如遭泄露，依法追究！

**Comment by LinXunFeng** [comment]
感谢您对本库的支持，由于本库依赖的 `SwiftyJSON` 停止维护已久，加上本人对库的维护时间十分有限，现决定停止维护，给您带来的不便敬请谅解！
