### ISSUE TITLE
必须手动映射才能获取到值，名称一样也拿不到值  求解

### ISSUE THREAD

**Issue by lesslee** [MoyaMapper/MoyaMapper#17]
mutating func mapping(_ json: JSON) {
        self.blog_id = json["id"].stringValue
        //想取出值  都要手动映射
       ......

    }

**Comment by LinXunFeng** [comment]
我这边试了没问题，麻烦你提供一下`Demo`

**Comment by LinXunFeng** [comment]
感谢您对本库的支持，由于本库依赖的 `SwiftyJSON` 停止维护已久，加上本人对库的维护时间十分有限，现决定停止维护，给您带来的不便敬请谅解！
