### ISSUE TITLE
关于 反射 设置对象值的问题

### ISSUE THREAD

**Issue by imzyf** [MoyaMapper/MoyaMapper#2]
let decoder = JSONDecoder()
        if let _model = try? decoder.decode(T.self, from: data) { model = _model }
        return model

能通过反射创建对象设置值吗？

还有没有其他的方法通过实例化对象 设置值？

**Comment by LinXunFeng** [comment]
不好意思，我没明白，是否可以提供一下示例代码？ @imzyf

**Comment by imzyf** [comment]
就是想请教一个问题：
能否通过反射创建对象 对对象属性赋值？

除了库中使用的 JSONDecoder() 生成对象，还有其他的方法吗？

**Comment by LinXunFeng** [comment]
可以的话，麻烦加我QQ吧（598600855），这样了解起来比较方便些 @imzyf
