### ISSUE TITLE
 Model与Dictionary的互转?

### ISSUE THREAD

**Issue by xwgit2971** [MoyaMapper/MoyaMapper#6]
现在有Model与JSON字符的互转, 但没有Dictionary, Data, JSON转换为Model常用的操作。

**Comment by LinXunFeng** [comment]
@xwgit2971  嗯，这两天我抽空加下，感谢反馈

**Comment by LinXunFeng** [comment]
@xwgit2971 行了，1.2.3版本已支持将Data、字典、json字符串 等转为 Modelable
```swift
/// Modelable -> mapping -> Model
static func mapModel(from object: Any) -> Self
/// Modelable -> mapping -> Models
static func mapModels(from object: Any) -> [Self]

/// Codeable -> Model
static func codeModel(from object: Any) -> Self
/// Codeable -> Models
static func codeModels(from object: Any) -> [Self]
```

Example
```swift
let model = models[0]
let jsonData = model.toData()
let jsonDict = model.toDictionary()
let jsonString = model.toJSONString()
let model1 = MyModel.mapModel(from: jsonData!)
let model2 = MyModel.mapModel(from: jsonDict)
let model3 = MyModel.mapModel(from: jsonString)
```

**Comment by xwgit2971** [comment]
`mapModel(from:)` 方法OK了。但是`codeModel(from:) `有问题, 解析出来的变量都是为默认值。而且看到文档里提到推荐使用`codeModel(from:) `

**Comment by LinXunFeng** [comment]
这个看你应用的场景，mapModel是经过mapping方法后才转换成Modelable的，而codeModel是直接转换成Modelable。
- 如果后台返回数据与你的模型的字段名有出入的话就用mapModel方法，如果没有出入，那用codeModel也是一样的效果。
- 但是，如果你是像我上面的Example一样是已经转换成Model了再转换出来的Data/字典/JSON字符串，那转换出来的这个数据是已经通过mapping修正过的了，这时就得用codeModel方法！因为修正后，之后有出入的字段已经没有了

**Comment by xwgit2971** [comment]
还是不太明白mapModel和codeModel的区别, 没有个通用的吗, 让使用者很疑惑. 
` throw DecodingError._typeMismatch(at: self.codingPath, expectation: [Any].self, reality: self.storage.topContainer)`
