### ISSUE TITLE
target最低版本设置为iOS10时报错

### ISSUE THREAD

**Issue by DamonHu** [MoyaMapper/MoyaMapper#8]
target最低版本设置为iOS10，pod设置为platform :ios, '10.0'时，MMCache因为基于iOS8.0会报错

**Comment by LinXunFeng** [comment]
我刚刚试了一下，不会呀

**Comment by DamonHu** [comment]
我创建了一个demo测试了下，是会报错的，因为想用最新的RxSwift，所以moya用了beta最新版本
```
platform :ios, '10.0'

target 'test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test
  pod 'Moya/RxSwift', '~> 14.0.0-beta.5'
  pod 'MoyaMapper'
  pod 'MoyaMapper/Rx'
  pod 'MoyaMapper/RxCache'
end
```

**Comment by DamonHu** [comment]
![image](https://user-images.githubusercontent.com/13430574/72598181-4539cb00-394a-11ea-8aaa-e228641389a5.png)

编译之后的报错信息

**Comment by LinXunFeng** [comment]
知道问题了，你现在还是用回Moya的正式版13吧。

Moya14beta最低的编译要求改为ios10了，目前MoyaMapper和Moya13还是ios8来着，而且Moay14还把Result给去掉了，所以强制修改MoyaMapper的编译版本为ios10也无法解决，这个等14这个版本正式出来后我再做版本升级吧。感谢你的反馈

**Comment by LinXunFeng** [comment]
请更新`MoyaMapper`版本至`3.0.0`
